# Generated by Django 3.1.12 on 2025-02-23 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot2025',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REFRENCENUMBER', models.CharField(max_length=20)),
                ('DEPOT', models.CharField(max_length=100)),
                ('AREA_ENGINEER_NAME', models.CharField(max_length=100)),
                ('BLOCKNUMBER', models.CharField(max_length=20)),
                ('SUBSTATIONNUMBER', models.CharField(max_length=20)),
                ('TX', models.CharField(max_length=10)),
                ('FEEDERNUMBER', models.CharField(max_length=10)),
                ('LVBNUMBER', models.CharField(max_length=10)),
                ('TYPE', models.CharField(max_length=50)),
                ('WAYLEAVENUMBER', models.CharField(max_length=100)),
                ('USPDATE', models.DateField(blank=True, null=True)),
                ('PASSEDDATE', models.DateField(blank=True, null=True)),
                ('REMARKES', models.TextField(blank=True)),
                ('PlanStatus', models.CharField(max_length=50)),
                ('ConStatus', models.CharField(max_length=50)),
                ('GISDATE', models.DateField(blank=True, null=True)),
                ('RCCDATE', models.DateField(blank=True, null=True)),
                ('MSPDATE', models.DateField(blank=True, null=True)),
                ('labourcost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ministrycost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cable_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Area', models.CharField(blank=True, max_length=100)),
                ('gov', models.CharField(max_length=100)),
                ('sentDate', models.DateField(blank=True, null=True)),
                ('noOfServ', models.IntegerField()),
                ('noOfFaults', models.IntegerField()),
                ('areaEngEmail', models.EmailField(blank=True, max_length=254)),
                ('EngPhoneNumber', models.CharField(blank=True, max_length=15)),
                ('AreaOfAe', models.CharField(max_length=100)),
                ('totalcost', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpr', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
