# Generated by Django 3.1.12 on 2025-02-24 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='depotcases2024',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('REFRENCENUMBER', models.CharField(max_length=20)),
                ('DEPOT', models.CharField(max_length=100)),
                ('AREA_ENGINEER_NAME', models.CharField(max_length=100)),
                ('BLOCKNUMBER', models.CharField(max_length=20)),
                ('SUBSTATIONNUMBER', models.CharField(max_length=20)),
                ('TX', models.CharField(max_length=10)),
                ('FEEDERNUMBER', models.CharField(max_length=10)),
                ('LVBNUMBER', models.CharField(max_length=10)),
                ('TYPE', models.CharField(max_length=50)),
                ('WAYLEAVENUMBER', models.CharField(max_length=100)),
                ('USPDATE', models.DateField(blank=True, null=True)),
                ('PASSEDDATE', models.DateField(blank=True, null=True)),
                ('REMARKES', models.TextField(blank=True)),
                ('PlanStatus', models.CharField(max_length=50)),
                ('ConStatus', models.CharField(max_length=50)),
                ('GISDATE', models.DateField(blank=True, null=True)),
                ('RCCDATE', models.DateField(blank=True, null=True)),
                ('MSPDATE', models.DateField(blank=True, null=True)),
                ('labourcost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ministrycost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cable_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Area', models.CharField(blank=True, max_length=100)),
                ('gov', models.CharField(max_length=100)),
                ('sentDate', models.DateField(blank=True, null=True)),
                ('noOfServ', models.IntegerField()),
                ('noOfFaults', models.IntegerField()),
                ('areaEngEmail', models.EmailField(blank=True, max_length=254)),
                ('EngPhoneNumber', models.CharField(blank=True, max_length=15)),
                ('AreaOfAe', models.CharField(max_length=100)),
                ('totalcost', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'depotcases2024',
            },
        ),
        migrations.CreateModel(
            name='depotcases2025',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('REFRENCENUMBER', models.CharField(max_length=20)),
                ('DEPOT', models.CharField(max_length=100)),
                ('AREA_ENGINEER_NAME', models.CharField(max_length=100)),
                ('BLOCKNUMBER', models.CharField(max_length=20)),
                ('SUBSTATIONNUMBER', models.CharField(max_length=20)),
                ('TX', models.CharField(max_length=10)),
                ('FEEDERNUMBER', models.CharField(max_length=10)),
                ('LVBNUMBER', models.CharField(max_length=10)),
                ('TYPE', models.CharField(max_length=50)),
                ('WAYLEAVENUMBER', models.CharField(max_length=100)),
                ('USPDATE', models.DateField(blank=True, null=True)),
                ('PASSEDDATE', models.DateField(blank=True, null=True)),
                ('REMARKES', models.TextField(blank=True)),
                ('PlanStatus', models.CharField(max_length=50)),
                ('ConStatus', models.CharField(max_length=50)),
                ('GISDATE', models.DateField(blank=True, null=True)),
                ('RCCDATE', models.DateField(blank=True, null=True)),
                ('MSPDATE', models.DateField(blank=True, null=True)),
                ('labourcost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ministrycost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cable_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Area', models.CharField(blank=True, max_length=100)),
                ('gov', models.CharField(max_length=100)),
                ('sentDate', models.DateField(blank=True, null=True)),
                ('noOfServ', models.IntegerField()),
                ('noOfFaults', models.IntegerField()),
                ('areaEngEmail', models.EmailField(blank=True, max_length=254)),
                ('EngPhoneNumber', models.CharField(blank=True, max_length=15)),
                ('AreaOfAe', models.CharField(max_length=100)),
                ('totalcost', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'depotcases2025',
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Number', models.CharField(max_length=50, unique=True, verbose_name='Permit Number')),
                ('Stage', models.CharField(max_length=100, verbose_name='Stage')),
                ('Status', models.CharField(max_length=100, verbose_name='Status')),
                ('Area', models.CharField(max_length=100, verbose_name='Area')),
                ('Parcel_Number', models.CharField(max_length=50, verbose_name='Parcel Number')),
                ('Block', models.CharField(max_length=50, verbose_name='Block')),
                ('KW', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='KW')),
                ('KVA', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='KVA')),
                ('PlanEng', models.CharField(max_length=100, verbose_name='Plan Engineer')),
                ('Plan_Status', models.CharField(max_length=100, verbose_name='Plan Status')),
                ('PASSED_DATE', models.DateField(verbose_name='Passed Date')),
                ('TO_WL_DATE', models.DateField(verbose_name='To WL Date')),
                ('TO_GIS_DATE', models.DateField(verbose_name='To GIS Date')),
                ('WL_NUMBER', models.CharField(max_length=100, verbose_name='WL_NUMBER')),
                ('REF_NO', models.CharField(max_length=100, verbose_name='REF_NO')),
                ('comment', models.CharField(max_length=100, verbose_name='comment')),
            ],
            options={
                'db_table': 'Permit',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpr', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
