# Generated by Django 3.1.12 on 2025-02-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depotcases2024',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='depotcases2024',
            name='AreaOfAe',
        ),
        migrations.RemoveField(
            model_name='depotcases2024',
            name='DEPOT',
        ),
        migrations.RemoveField(
            model_name='depotcases2024',
            name='EngPhoneNumber',
        ),
        migrations.RemoveField(
            model_name='depotcases2024',
            name='gov',
        ),
        migrations.RemoveField(
            model_name='depotcases2024',
            name='sentDate',
        ),
        migrations.RemoveField(
            model_name='depotcases2025',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='depotcases2025',
            name='AreaOfAe',
        ),
        migrations.RemoveField(
            model_name='depotcases2025',
            name='DEPOT',
        ),
        migrations.RemoveField(
            model_name='depotcases2025',
            name='EngPhoneNumber',
        ),
        migrations.RemoveField(
            model_name='depotcases2025',
            name='gov',
        ),
        migrations.RemoveField(
            model_name='depotcases2025',
            name='sentDate',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='Block',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='KVA',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='KW',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='PASSED_DATE',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='Parcel_Number',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='PlanEng',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='Plan_Status',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='REF_NO',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='Stage',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='TO_GIS_DATE',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='TO_WL_DATE',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='WL_NUMBER',
        ),
        migrations.AddField(
            model_name='permit',
            name='block',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Block'),
        ),
        migrations.AddField(
            model_name='permit',
            name='kva',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='parcel_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parcel Number'),
        ),
        migrations.AddField(
            model_name='permit',
            name='passed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Passed Date'),
        ),
        migrations.AddField(
            model_name='permit',
            name='plan_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan Status'),
        ),
        migrations.AddField(
            model_name='permit',
            name='planeng',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan Engineer'),
        ),
        migrations.AddField(
            model_name='permit',
            name='ref_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='REF_NO'),
        ),
        migrations.AddField(
            model_name='permit',
            name='to_gis_date',
            field=models.DateField(blank=True, null=True, verbose_name='To GIS Date'),
        ),
        migrations.AddField(
            model_name='permit',
            name='to_wl_date',
            field=models.DateField(blank=True, null=True, verbose_name='To WL Date'),
        ),
        migrations.AddField(
            model_name='permit',
            name='wl_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WL_NUMBER'),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='AREA_ENGINEER_NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='BLOCKNUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='ConStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='FEEDERNUMBER',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='LVBNUMBER',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='PlanStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='REFRENCENUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='REMARKES',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='SUBSTATIONNUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='TX',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='TYPE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='WAYLEAVENUMBER',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='areaEngEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='cable_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='labourcost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='ministrycost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='noOfFaults',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='noOfServ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='totalcost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='AREA_ENGINEER_NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='BLOCKNUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='ConStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='FEEDERNUMBER',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='LVBNUMBER',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='PlanStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='REFRENCENUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='REMARKES',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='SUBSTATIONNUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='TX',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='TYPE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='WAYLEAVENUMBER',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='areaEngEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='cable_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='labourcost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='ministrycost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='noOfFaults',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='noOfServ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='totalcost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='Number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Permit Number'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
