# Generated by Django 3.1.12 on 2025-02-23 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Permit Number')),
                ('stage', models.CharField(max_length=100, verbose_name='Stage')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('area', models.CharField(max_length=100, verbose_name='Area')),
                ('parcel_number', models.CharField(max_length=50, verbose_name='Parcel Number')),
                ('block', models.CharField(max_length=50, verbose_name='Block')),
                ('last_action_date', models.DateTimeField(verbose_name='Last Action Date')),
                ('certificate_expiry_date', models.DateTimeField(verbose_name='Certificate Expiry Date')),
                ('kw', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='KW')),
                ('kva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='KVA')),
                ('plan_eng', models.CharField(max_length=100, verbose_name='Plan Engineer')),
                ('plan_status', models.CharField(max_length=100, verbose_name='Plan Status')),
                ('passed_date', models.DateField(verbose_name='Passed Date')),
                ('to_wl_date', models.DateField(verbose_name='To WL Date')),
                ('to_gis_date', models.DateField(verbose_name='To GIS Date')),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='Date Added')),
            ],
            options={
                'verbose_name': 'Building Permit',
                'verbose_name_plural': 'Building Permits',
            },
        ),
        migrations.DeleteModel(
            name='Depot2025',
        ),
    ]
