# Generated by Django 3.1.12 on 2025-02-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotcases2024',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
