# Generated by Django 5.1.6 on 2025-03-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0002_auto_20250227_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadReading2024',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ssno', models.CharField(max_length=20, verbose_name='SSNO')),
                ('txno', models.CharField(blank=True, max_length=20, null=True, verbose_name='TXNO')),
                ('block', models.CharField(blank=True, max_length=20, null=True, verbose_name='BLOCK')),
                ('lvb_fdr', models.CharField(blank=True, max_length=20, null=True, verbose_name='LVB FDR')),
                ('kva', models.CharField(blank=True, max_length=20, null=True, verbose_name='kVA')),
                ('worktype', models.CharField(blank=True, max_length=255, null=True, verbose_name='WorkType')),
                ('plan_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Plan Status')),
                ('wl_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='WL NO')),
                ('sch_ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sch Ref')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('job_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job no')),
                ('rcvd_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rcvd Date')),
                ('planeng', models.CharField(blank=True, max_length=255, null=True, verbose_name='PlanEng')),
                ('consteng', models.CharField(blank=True, max_length=255, null=True, verbose_name='ConstEng')),
                ('plan_rem', models.TextField(blank=True, null=True, verbose_name='Plan Rem')),
                ('cons_rem', models.TextField(blank=True, null=True, verbose_name='Cons Rem')),
                ('labour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Labour')),
                ('material', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Material')),
                ('schemes_in_process', models.TextField(blank=True, null=True, verbose_name='Schemes In Process')),
                ('completed_by_construction', models.TextField(blank=True, null=True, verbose_name='Completed By Construction')),
                ('recieved_by_construction', models.TextField(blank=True, null=True, verbose_name='Recieved By Construction')),
                ('wayleave', models.TextField(blank=True, null=True, verbose_name='wayleave')),
                ('pending_with', models.TextField(blank=True, null=True, verbose_name='pending with')),
                ('passed_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='passed date')),
                ('gisdate', models.CharField(blank=True, max_length=255, null=True, verbose_name='GISDATE')),
                ('uspdate', models.CharField(blank=True, max_length=255, null=True, verbose_name='USPDATE')),
                ('rccdate', models.CharField(blank=True, max_length=255, null=True, verbose_name='RCCDATE')),
                ('mspdate', models.CharField(blank=True, max_length=255, null=True, verbose_name='MSPDATE')),
                ('labourcost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='labourcost')),
                ('ministrycost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ministrycost')),
                ('cable_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cable length')),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Area')),
                ('gov', models.CharField(blank=True, max_length=255, null=True, verbose_name='gov')),
                ('consremarks', models.TextField(blank=True, null=True, verbose_name='ConsRemarks')),
                ('totalcost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='totalcost')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
