# Generated by Django 3.1.12 on 2025-02-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0002_auto_20250223_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuildingPermit',
        ),
    ]
