# Generated by Django 3.1.12 on 2025-02-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0002_auto_20250224_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
