# Generated by Django 3.1.12 on 2025-02-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0004_auto_20250225_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depotcases2024',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='depotcases2024',
            name='AreaOfAe',
        ),
        migrations.RemoveField(
            model_name='depotcases2024',
            name='DEPOT',
        ),
        migrations.RemoveField(
            model_name='depotcases2024',
            name='EngPhoneNumber',
        ),
        migrations.RemoveField(
            model_name='depotcases2024',
            name='gov',
        ),
        migrations.RemoveField(
            model_name='depotcases2024',
            name='sentDate',
        ),
        migrations.RemoveField(
            model_name='depotcases2025',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='depotcases2025',
            name='AreaOfAe',
        ),
        migrations.RemoveField(
            model_name='depotcases2025',
            name='DEPOT',
        ),
        migrations.RemoveField(
            model_name='depotcases2025',
            name='EngPhoneNumber',
        ),
        migrations.RemoveField(
            model_name='depotcases2025',
            name='gov',
        ),
        migrations.RemoveField(
            model_name='depotcases2025',
            name='sentDate',
        ),
        migrations.AlterField(
            model_name='permit',
            name='passed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Passed Date'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='to_gis_date',
            field=models.DateField(blank=True, null=True, verbose_name='To GIS Date'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='to_wl_date',
            field=models.DateField(blank=True, null=True, verbose_name='To WL Date'),
        ),
    ]
