# Generated by Django 5.1.6 on 2025-03-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0005_rename_block_loadreading2024_block_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadreading2024',
            old_name='ID',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='loadreading2024',
            name='WorkType',
        ),
    ]
