# Generated by Django 5.1.6 on 2025-03-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0006_rename_id_loadreading2024_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='loadreading2025',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SSNO', models.CharField(max_length=20, verbose_name='SSNO')),
                ('TXNO', models.CharField(blank=True, max_length=20, null=True, verbose_name='TXNO')),
                ('BLOCK', models.CharField(blank=True, max_length=20, null=True, verbose_name='BLOCK')),
                ('LVB_FDR', models.CharField(blank=True, max_length=20, null=True, verbose_name='LVB FDR')),
                ('KVA', models.CharField(blank=True, max_length=20, null=True, verbose_name='kVA')),
                ('Plan_Status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Plan Status')),
                ('Sch_Ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sch Ref')),
                ('PlanEng', models.CharField(blank=True, max_length=255, null=True, verbose_name='PlanEng')),
                ('Labour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Labour')),
                ('Material', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Material')),
                ('CONST_COMP', models.TextField(blank=True, null=True, verbose_name='Completed By Construction')),
                ('WL_NO', models.TextField(blank=True, null=True, verbose_name='wayleave')),
                ('passed_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='passed date')),
                ('GISDATE', models.CharField(blank=True, max_length=255, null=True, verbose_name='GISDATE')),
                ('USPDATE', models.CharField(max_length=255, verbose_name='USPDATE')),
                ('RCCDATE', models.CharField(blank=True, max_length=255, null=True, verbose_name='RCCDATE')),
                ('MSPDATE', models.CharField(blank=True, max_length=255, null=True, verbose_name='MSPDATE')),
                ('labourcost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='labourcost')),
                ('ministrycost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ministrycost')),
                ('cable_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cable length')),
                ('totalcost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='totalcost')),
            ],
        ),
    ]
