# Generated by Django 5.1.6 on 2025-03-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0007_loadreading2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadreading2024',
            name='Labour',
            field=models.FloatField(blank=True, null=True, verbose_name='Labour'),
        ),
        migrations.AlterField(
            model_name='loadreading2024',
            name='Material',
            field=models.FloatField(blank=True, null=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='loadreading2024',
            name='cable_length',
            field=models.FloatField(blank=True, null=True, verbose_name='cable length'),
        ),
        migrations.AlterField(
            model_name='loadreading2024',
            name='labourcost',
            field=models.FloatField(blank=True, null=True, verbose_name='labourcost'),
        ),
        migrations.AlterField(
            model_name='loadreading2024',
            name='ministrycost',
            field=models.FloatField(blank=True, null=True, verbose_name='ministrycost'),
        ),
        migrations.AlterField(
            model_name='loadreading2024',
            name='totalcost',
            field=models.FloatField(blank=True, null=True, verbose_name='totalcost'),
        ),
    ]
