# Generated by Django 5.1.6 on 2025-03-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0008_alter_loadreading2024_labour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadreading2024',
            name='cable_length',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='cable length'),
        ),
    ]
