# Generated by Django 3.1.12 on 2025-02-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0009_auto_20250226_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotcases2024',
            name='AREA_ENGINEER_NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='BLOCKNUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='ConStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='FEEDERNUMBER',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='LVBNUMBER',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='PlanStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='REFRENCENUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='REMARKES',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='SUBSTATIONNUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='TX',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='TYPE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='WAYLEAVENUMBER',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='areaEngEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='cable_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='labourcost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='ministrycost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='noOfFaults',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='noOfServ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2024',
            name='totalcost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='AREA_ENGINEER_NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='BLOCKNUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='ConStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='FEEDERNUMBER',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='LVBNUMBER',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='PlanStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='REFRENCENUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='REMARKES',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='SUBSTATIONNUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='TX',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='TYPE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='WAYLEAVENUMBER',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='areaEngEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='cable_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='labourcost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='ministrycost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='noOfFaults',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='noOfServ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depotcases2025',
            name='totalcost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='Number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Permit Number'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='block',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Block'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='kva',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='parcel_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parcel Number'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='plan_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan Status'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='planeng',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan Engineer'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='ref_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='REF_NO'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='wl_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WL_NUMBER'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
