# Generated by Django 5.1.7 on 2025-03-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0009_alter_loadreading2024_cable_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadreading2024',
            name='Plan_Status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Plan_Status'),
        ),
        migrations.AlterField(
            model_name='loadreading2024',
            name='cable_length',
            field=models.FloatField(blank=True, null=True, verbose_name='cable length'),
        ),
    ]
