# Generated by Django 3.1.12 on 2025-02-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0010_auto_20250226_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotcases2025',
            name='labourcost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
